server:
  port: 8653

spring:
  application:
    name: ms-auth
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://164.132.197.173:8651/eureka/

shuaicj:
  security:
    jwt:
      secret: otherpeopledontknowit
