server:
  port: 8649

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8651/eureka/

spring:
  application:
    name: ms-client

  #Configurations H2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true

#Nos configurations
test-config:
  test: 3
