server:
  port: 8641

spring:
  application:
    name: ms-topics
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://164.132.197.173:8741/db_VL-topics
    username: usr_topics
    password: topics
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://164.132.197.173:8651/eureka/

