server:
  port: 8641

spring:
  application:
    name: ms-topics

#Configurations H2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://164.132.197.173:8651/eureka/

