server:
  port: 8651

spring:
  application:
    name: vl-eureka-server
  main:
      allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8651/eureka/
    register-with-eureka: false
    fetch-registry: false




