server:
  port: 8652

spring:
  application:
    name: zuul-server
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8651/eureka/

zuul:
  routes:
    ms-users:
      url: http://localhost:8640/ms-users/
    ms-topics:
      url: http://localhost:8641/ms-topics/