
#server:
#  port: 8652
#
#spring:
#  application:
#    name: zuul-server
#  main:
#    allow-bean-definition-overriding: true
#  security:
#    user:
#      name: julien
#      password: 1947147
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://164.132.197.173:8651/eureka/
#
#zuul:
#  routes:
#    ms-users:
#      url: http://164.132.197.173:8640/
#    ms-topics:
#      url: http://164.132.197.173:8641/

server:
  port: 8652

spring:
  application:
    name: zuul-server
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: utilisateur
      password: mdp

eureka:
  client:
    serviceUrl:
      defaultZone: http://164.132.197.173:8651/eureka/

zuul:
  routes:
    auth-center:
      path: /login/**
      ##url: http://164.132.197.173:2344/
      url: http://localhost:2346/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    ms-users:
      url: http://164.132.197.173:8640/
      path: /ms-users/**
      ##sensitiveHeaders: Cookie,Set-Cookie
      ##stripPrefix: false
    ms-topics:
      url: http://164.132.197.173:8641/
      path: /ms-topics/**
    ms-campaign:
      url: http://164.132.197.173:8642/
      path: /ms-campaign/**

############### added ############
    ##auth-center:
    ##  path: /login/**
    ##  url: http://127.0.0.1:8081/
    ##  sensitiveHeaders: Cookie,Set-Cookie
    ##  stripPrefix: false
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:8082/

jwt.security.jwt.secret: otherpeopledontknowit


ms.passphrase.security: bidon
ms.passphrase.key: security-passphrase
