server:
    port: 8652
spring:
    application:
        name: zuul-server

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8651/eureka/

#a adapter
zuul:
    routes:
        ms-users:
            url: http://localhost:8640/ms-users/
        ms-topics:
            url: http://localhost:8641/ms-topics/



#a adapter
security:
    user:
        name: root
        password: password
    oauth2:
        client:
            accessTokenUri: http://localhost:8765/login/oauth/token
            userAuthorizationUri: http://localhost:8765/login/oauth/authorize
            clientAuthenticationScheme: form
        resource:
            userInfoUri: http://localhost:8765/uaa/user
            preferTokenInfo: false
    sessions: ALWAYS