server:
  port: 8652

spring:
  application:
    name: zuul-server
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: utilisateur
      password: mdp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8651/eureka/

zuul:
  routes:
    ms-users:
      url: http://localhost:8640/
    ms-topics:
      url: http://localhost:8641/